from fastapi import APIRouter
from backend.app.routers import auth, docs, chapters, objects, datas, tables, charts, sentences, gendocs, settings, org, admin, llm, misc, menus, configs, i18n, codes, messages, terms, data_metas, data_cols, popups, connectors, docgroups, datasets, apps, llmkeys, notifications, whitelists, payments, auditlogs, content_purge
from d2chat import routes as d2chat
from d2insight.chat import router as d2insight

router = APIRouter()
router.include_router(auth.router,      prefix="/auth",      tags=["auth"])
router.include_router(docs.router,      prefix="/docs",      tags=["docs"])
router.include_router(chapters.router,  prefix="/chapters",  tags=["chapters"])
router.include_router(objects.router,   prefix="/objects",   tags=["objects"])
router.include_router(datas.router,     prefix="/datas",     tags=["datas"])
router.include_router(tables.router,    prefix="/tables",    tags=["tables"])
router.include_router(charts.router,    prefix="/charts",    tags=["charts"])
router.include_router(sentences.router, prefix="/sentences", tags=["sentences"])
router.include_router(gendocs.router,   prefix="/gendocs",   tags=["gendocs"])
router.include_router(settings.router,  prefix="/settings",  tags=["settings"])
router.include_router(org.router,       prefix="/org",       tags=["org"])
router.include_router(admin.router,     prefix="/admin",     tags=["admin"])
router.include_router(llm.router,       prefix="/llm",       tags=["llm"])
router.include_router(misc.router,      prefix="/misc",      tags=["misc"])
router.include_router(menus.router,     prefix="/menus",     tags=["menus"])
router.include_router(configs.router,   prefix="/configs",   tags=["configs"])
router.include_router(i18n.router,      prefix="/i18n",      tags=["i18n"])
router.include_router(codes.router,     prefix="/codes",     tags=["codes"])
router.include_router(messages.router,  prefix="/messages",  tags=["messages"])
router.include_router(terms.router,      prefix="/terms",      tags=["terms"])
router.include_router(data_metas.router, prefix="/data-metas", tags=["data-metas"])
router.include_router(data_cols.router,  prefix="/data-cols",  tags=["data-cols"])
router.include_router(popups.router,      prefix="/popups",      tags=["popups"])
router.include_router(connectors.router,  prefix="/connectors",  tags=["connectors"])
router.include_router(docgroups.router,   prefix="/docgroups",   tags=["docgroups"])
router.include_router(datasets.router,    prefix="/datasets",    tags=["datasets"])
router.include_router(apps.router,        prefix="/apps",        tags=["apps"])
router.include_router(d2chat.router,      prefix="/d2chat",      tags=["d2chat"])
router.include_router(d2insight.router,   prefix="/d2insight",   tags=["d2insight"])
router.include_router(llmkeys.router,     prefix="/llmkeys",     tags=["llmkeys"])
router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
router.include_router(whitelists.router,  prefix="/whitelists",  tags=["whitelists"])
router.include_router(payments.router,    prefix="/payments",    tags=["payments"])
router.include_router(auditlogs.router,   prefix="/auditlogs",   tags=["auditlogs"])
router.include_router(content_purge.router, prefix="/content-purge", tags=["content-purge"])
