# 분석 파라미터 상수 (환경변수 미사용 — env 로딩은 backend/app/config.py에서 담당)
ABC_THRESHOLDS = (0.70, 0.90)
XYZ_THRESHOLDS = (0.20, 0.50)
ANALYSIS_TARGETS = ["AZ", "AX", "AY", "BZ"]
SHAPLEY_ITERATIONS = 500
TOP_N_MAX = 5
PARETO_THRESHOLD = 0.80
MIN_CONTRIBUTION = 0.05
DRILLDOWN_DEPTH = 2
DRILLDOWN_MIN_CELL_SHARE = 0.001
DIMENSIONS = ["채널", "제품대분류", "제품중분류", "지역"]
REGION_LEVEL = "Country"

NEW_DISC_HIGH_IMPACT_RATIO = 0.30
OUTLIER_CHANGE_PCT = 0.30
OUTLIER_MIN_REVENUE_SHARE = 0.01

ANOMALY_SURGE_CRITICAL = 2.00
ANOMALY_NORMAL_HIGH    = 1.10
ANOMALY_NORMAL_LOW     = 0.90
ANOMALY_CRITICAL       = 0.70
ANOMALY_CAUTION        = 0.70   # _severity() 함수 호환용 (= ANOMALY_CRITICAL)

ANOMALY_SIGMA: float = 3.0
COMPARE_TYPE: str = "MoM"

REPORT_FONT_PATH: str = ""  # 미설정 시 OS 기본 폰트 자동 탐색
